(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}},r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,e){if(a==Array.prototype||a==Object.prototype)return a;a[c]=e.value;return a},t=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var e=a[c];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");
},u=t(this),v=function(a,c){if(c)a:{var e=u;a=a.split(".");for(var f=0;f<a.length-1;f++){var g=a[f];if(!(g in e))break a;e=e[g]}a=a[a.length-1];f=e[a];c=c(f);c!=f&&null!=c&&r(e,a,{configurable:!0,writable:!0,value:c})}},z=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:n(a)}};
v("Promise",function(a){function c(){this.g=null}function e(b){return b instanceof g?b:new g(function(d){d(b)})}if(a)return a;c.prototype.u=function(b){if(null==this.g){this.g=[];var d=this;this.v(function(){d.M()})}this.g.push(b)};var f=u.setTimeout;c.prototype.v=function(b){f(b,0)};c.prototype.M=function(){for(;this.g&&this.g.length;){var b=this.g;this.g=[];for(var d=0;d<b.length;++d){var h=b[d];b[d]=null;try{h()}catch(k){this.L(k)}}}this.g=null};c.prototype.L=function(b){this.v(function(){throw b;
})};var g=function(b){this.i=0;this.j=void 0;this.h=[];this.F=!1;var d=this.o();try{b(d.resolve,d.reject)}catch(h){d.reject(h)}};g.prototype.o=function(){function b(k){return function(l){h||(h=!0,k.call(d,l))}}var d=this,h=!1;return{resolve:b(this.R),reject:b(this.s)}};g.prototype.R=function(b){if(b===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof g)this.T(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=!0;break a;default:d=!1}d?
this.P(b):this.D(b)}};g.prototype.P=function(b){var d=void 0;try{d=b.then}catch(h){this.s(h);return}"function"==typeof d?this.U(d,b):this.D(b)};g.prototype.s=function(b){this.I(2,b)};g.prototype.D=function(b){this.I(1,b)};g.prototype.I=function(b,d){if(0!=this.i)throw Error("Cannot settle("+b+", "+d+"): Promise already settled in state"+this.i);this.i=b;this.j=d;2===this.i&&this.S();this.N()};g.prototype.S=function(){var b=this;f(function(){if(b.O()){var d=u.console;"undefined"!==typeof d&&d.error(b.j)}},
1)};g.prototype.O=function(){if(this.F)return!1;var b=u.CustomEvent,d=u.Event,h=u.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof b?b=new b("unhandledrejection",{cancelable:!0}):"function"===typeof d?b=new d("unhandledrejection",{cancelable:!0}):(b=u.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.j;return h(b)};g.prototype.N=function(){if(null!=this.h){for(var b=0;b<this.h.length;++b)q.u(this.h[b]);this.h=null}};
var q=new c;g.prototype.T=function(b){var d=this.o();b.l(d.resolve,d.reject)};g.prototype.U=function(b,d){var h=this.o();try{b.call(d,h.resolve,h.reject)}catch(k){h.reject(k)}};g.prototype.then=function(b,d){function h(m,p){return"function"==typeof m?function(w){try{k(m(w))}catch(x){l(x)}}:p}var k,l,y=new g(function(m,p){k=m;l=p});this.l(h(b,k),h(d,l));return y};g.prototype.catch=function(b){return this.then(void 0,b)};g.prototype.l=function(b,d){function h(){switch(k.i){case 1:b(k.j);break;case 2:d(k.j);
break;default:throw Error("Unexpected state: "+k.i);}}var k=this;null==this.h?q.u(h):this.h.push(h);this.F=!0};g.resolve=e;g.reject=function(b){return new g(function(d,h){h(b)})};g.race=function(b){return new g(function(d,h){for(var k=z(b),l=k.next();!l.done;l=k.next())e(l.value).l(d,h)})};g.all=function(b){var d=z(b),h=d.next();return h.done?e([]):new g(function(k,l){function y(w){return function(x){m[w]=x;p--;0==p&&k(m)}}var m=[],p=0;do m.push(void 0),p++,e(h.value).l(y(m.length-1),l),h=d.next();
while(!h.done)})};return g});
var A=this||self,B=function(a,c){a=a.split(".");var e=A;a[0]in e||"undefined"==typeof e.execScript||e.execScript("var "+a[0]);for(var f;a.length&&(f=a.shift());)a.length||void 0===c?e=e[f]&&e[f]!==Object.prototype[f]?e[f]:e[f]={}:e[f]=c},C=function(a,c){function e(){}e.prototype=c.prototype;a.Y=c.prototype;a.prototype=new e;a.prototype.constructor=a;a.X=function(f,g,q){for(var b=Array(arguments.length-2),d=2;d<arguments.length;d++)b[d-2]=arguments[d];return c.prototype[g].apply(f,b)}},D=function(a){return a};/*

 SPDX-License-Identifier: Apache-2.0
*/
function E(a,c){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var e=Error().stack;e&&(this.stack=e)}a&&(this.message=String(a));void 0!==c&&(this.cause=c)}C(E,Error);E.prototype.name="CustomError";function F(a,c){a=a.split("%s");for(var e="",f=a.length-1,g=0;g<f;g++)e+=a[g]+(g<c.length?c[g]:"%s");E.call(this,e+a[f])}C(F,E);F.prototype.name="AssertionError";var G=function(a,c){throw new F("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var H;var K=function(a,c){this.J=a===I&&c||"";this.K=J};K.prototype.toString=function(){return"Const{"+this.J+"}"};var J={},I={};var M=function(a,c){this.H=c===L?a:""};M.prototype.toString=function(){return this.H+""};var N=function(a){if(a instanceof M&&a.constructor===M)return a.H;var c=typeof a;G("expected object of type TrustedResourceUrl, got '"+a+"' of type "+("object"!=c?c:a?Array.isArray(a)?"array":c:"null"));return"type_error:TrustedResourceUrl"},L={};function O(a){var c,e,f=null==(e=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:e.call(c,"script[nonce]");(c=f?f.nonce||f.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var P=function(a){var c;this.W=c=void 0===c?window:c;a instanceof K&&a.constructor===K&&a.K===J?a=a.J:(G("expected object of type Const, got '"+a+"'"),a="type_error:Const");if(void 0===H){c=null;var e=A.trustedTypes;if(e&&e.createPolicy)try{c=e.createPolicy("goog#html",{createHTML:D,createScript:D,createScriptURL:D})}catch(f){A.console&&A.console.error(f.message)}H=c}a=(c=H)?c.createScriptURL(a):a;this.V=new M(a,L);this.A=[];this.B=[];this.G=this.C=!1},Q=function(a){a.m.onload=function(){};a.m.onerror=
function(){};a.m.onreadystatechange=function(){}},R=function(a){var c=a.W.document,e=c.head||c.documentElement,f=c.createElement("script");a.m=f;f.async=!0;f.defer=!0;f.src=N(a.V);O(f);f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||(a.G=!0,Q(a),a.A.forEach(function(g){return g()}))};f.onerror=function(){a.C=!0;Q(a);a.B.forEach(function(g){return g()})};e.appendChild(f)};
P.prototype.load=function(a,c){this.G?a():this.A.push(a);this.C?c():this.B.push(c);this.m||R(this)};function S(a,c){var e=new P(a);B(c,function(f,g){f=void 0===f?function(){}:f;g=void 0===g?function(){}:g;return new Promise(function(q,b){e.load(function(){q();f()},function(){b();g()})})})}S(new K(I,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20220801_00_RC00/cloudshell/cloudshell.js"),"google.devops.tools.loadCloudShell");S(new K(I,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20220801_00_RC00/walkthrough/walkthrough.js"),"google.devops.tools.loadWalkthrough");}).call(this);
